# change the followings to match your Github username and repo name
baseurl: "/" # the name of your github repo
url: "https://fuugul.com" # the url of your github pages

# site information used in page title, meta data etc.
title: "Fuugul"
description: Fuugul

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Fuugul
author-bio: Zombie  # change to false to hide
author-image: me.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: false

nav-menu:
- text: Commissions
  permalink: commissions

# use false to turn off any social media links
twitter: https://twitter.com/fuugul
facebook: false
instagram: false
github: false
linkedin: false
medium: false
google-scholar: false
email: zombie@fuugul.com

# footer information
footer-msg: "Fuugul"
footer-msg-link: https://fuugul.com

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
